# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.GithubRepoStarsCountPlugin}}
#plugins:
#  # Automatically fetch Github repo star count
#  - GithubRepoStarsCountPlugin:
#      - ZhgChgLi/ZMarkupParser
#      - ZhgChgLi/ZReviewTender
#      - ZhgChgLi/ZMediumToMarkdown
#     - ZhgChgLi/linkyee

# Google Analytics tracking id
#google_analytics_id:

# HTML Title
title: "Rehan Azmat Linktree"

# Avatar image path
avatar: "./images/profile.jpg"

# Name section text
name: "@RehanAzmatNY"

# Tagline section text
tagline: >-
    A technology professional who specializes in the modernization of NYC government applications

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-blog"
      text: "Personal Blog"
      url: "https://www.google.com"
      alt: "Rehan's Tech Blog"
      title: "Rehan's Tech Blog"
      target: "_blank"
  - link:
      icon: "fa-brands fa-linkedin"
      text: "LinkedIn"
      url: "https://www.linkedin.com/in/rehanazmat/"
      alt: "LinkedIn"
      title: "LinkedIn"
      target: "_blank"
  - link:
      icon: "fa-solid fa-file"
      text: "Resume"
      url: "https://rehanazmat.s3.amazonaws.com/RAzmat+Resume.pdf"
      alt: "Rehan Azmat Resume"
      title: "Rehan Azmat Resume"
      target: "_blank"
 - link:
      icon: "fa-brands fa-github"
      text: "github"
      url:  "https://github.com/RehanAzmatNY"
      alt: "GitHub"
      title: "GitHub"
      target: "_blank"
  - link:
      icon: "fa-solid fa-envelope"
      url: "mailto:Rehan.Azmat.NY@gmail.com?Subject: Re:%20R.%20Azmat%20Resume"
      title: "Email: Rehan.Azmat.NY@gmail.com"
      alt: "Rehan.Azmat.NY@gmail.com"
      target: "_blank"
  - link:
      icon: "fa-solid fa-qrcode"
      text: "QR Code"
      url: "https://github.com/ZhgChgLi/ZMediumToMarkdown"
      alt: "QR Code"
      title: "QR Code"
      target: "_blank"

# Footer text
footer: >
   Follow my GKLY blog, GitHub, or connect with me on LinkedIn.

# Footer greeting
copyright: >
 Thank You for Visiting
